# Generated by Django 5.0 on 2023-12-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0004_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.CharField(blank=True, default='author', max_length=100),
        ),
    ]
