# Generated by Django 5.0 on 2023-12-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0006_remove_customuser_role_customuser_is_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='role',
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='drf.interest'),
        ),
    ]
